section .text
  global main

  main:


section .data
  NUM1 DB ? ; ? STANDS FOR BLANK VALUE
  NUM2 DB ? ; VARIABLE-NAME DEFINE-DIRECTIVE (DB = DEFINE BYTE) INITIAL-VALUE
  RESULT DB ? ; VALUES ARE STORED AS HEXADECIMAL
  MSG1 DB 10, 13, "ENTER FIRST NUMBER TO ADD : $"
  MSG2 DB 10, 13, "ENTER SECOND NUMBER TO ADD : $"
  MSG3 DB 10, 13, "RESULT OF THE ADDITION IS : $"
